/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description 数据库可用返回 200，不可用返回统一的 503 错误契约。
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description 列出「未归档」且「已经有消息」的会话。
         *
         *     两条筛选都是有意的：
         *
         *     - `mode`（可选）：篇 01「两种问答模式严格隔离」规定，两种模式的检索范围、
         *       matched_kp、追练推荐与学习事件**完全不同**。混在同一个列表里用户分不清
         *       哪条属于哪个范围，所以允许按模式取。
         *     - **空会话不返回**：没有任何消息的会话只是「点了一下新建」留下的残留。
         *       真实会话在发第一条问题时就会随事务写入 user 消息，因此这不会漏掉任何会话，
         *       只会让列表里剩下的每一条都能点开看。
         *
         *     契约：响应字段与原来完全一致；`mode` 是可选参数，不传即原来的行为。
         */
        get: operations["list_sessions_api_chat_sessions_get"];
        put?: never;
        /** Create Session */
        post: operations["create_session_api_chat_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Session
         * @description **物理删除**会话，连同它的消息与引用一起从库里移除。
         *
         *     2026-09-20 之前这里是**归档**（只置 `archived_at`），理由是「问答与引用要可追溯」。
         *     产品方明确要求列表里的 × 真的删掉记录，因此改成物理删除；
         *     该决策与取舍记在 `docs/reference-build-changes.md` 的 D-31。
         *
         *     按依赖顺序逐条删（引用 → 消息 → 会话），而不是只删会话行、靠数据库级联：
         *     模式里虽然声明了 `ON DELETE CASCADE`，但显式删除不依赖那份约束是否真的建成，
         *     换库或重建约束时也不会静默留下孤儿行。
         *
         *     注意：`learning_events.source_id` **故意没有外键**（见 `backend/models/learning.py`），
         *     所以这里不会、也不应该连带删除学习事件 —— 掌握度与弱信号是学习事实，
         *     不该因为用户清理了一轮对话就抹掉；代价是那几条事件的 `source_id` 会变成悬空 id。
         */
        delete: operations["delete_session_api_chat_sessions__session_id__delete"];
        options?: never;
        head?: never;
        /**
         * Rename Session
         * @description 会话标题仅供历史导航；不会改写消息、引用或学习事实。
         */
        patch: operations["rename_session_api_chat_sessions__session_id__patch"];
        trace?: never;
    };
    "/api/chat/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Messages */
        get: operations["list_messages_api_chat_sessions__session_id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/sessions/{session_id}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_api_chat_sessions__session_id__answers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/sessions/{session_id}/answers:stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask Stream */
        post: operations["ask_stream_api_chat_sessions__session_id__answers_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/sessions/{session_id}/followup-candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Followup Candidates
         * @description 只从服务端已归因叶子的既有题库读取候选；绝不在问答层造题或改掌握状态。
         */
        post: operations["followup_candidates_api_chat_sessions__session_id__followup_candidates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/sessions/{session_id}/mark-confused": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark Confused
         * @description 把困惑写成弱信号；它绝不伪造成作答、更不清空毕业证据。
         */
        post: operations["mark_confused_api_chat_sessions__session_id__mark_confused_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Today Plan
         * @description 没有今天的计划就返回 setup；页面据此渲染准备页，而不是直接塞题。
         */
        get: operations["read_today_plan_api_plans_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/today/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Today Plan
         * @description 生成动作只允许成功一次；“今天学什么”由用户在准备页确认后交给服务冻结。
         */
        post: operations["generate_today_plan_api_plans_today_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Plan Items */
        get: operations["read_plan_items_api_plans__plan_id__items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_id}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Append Plan Questions
         * @description 追加只从已有题库取题，永远是卷尾；不重洗、不生成、不显示来源。
         */
        post: operations["append_plan_questions_api_plans__plan_id__questions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/practice-items/{item_id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Practice Item Answer
         * @description 返回答案与解析。
         *
         *     这里**只读**：不写 revealed_at、不改掌握度、不影响毕业与复习计划、
         *     也不影响用户自评。做题前、中、后都可以调用。
         */
        get: operations["read_practice_item_answer_api_practice_items__item_id__answer_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/practice-items/{item_id}/self-assessments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Self Assessment
         * @description 一次自评的完整事务：attempt + 状态投影 + 审计事件一起提交。
         */
        post: operations["submit_self_assessment_api_practice_items__item_id__self_assessments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Knowledge Tree */
        get: operations["read_knowledge_tree_api_knowledge_tree_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/{kp_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Knowledge Node */
        get: operations["read_knowledge_node_api_knowledge__kp_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/{kp_id}/self-assessment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Node Self Assessment
         * @description 叶子整体自评：mastered 只写 2 个透明基础确认，绝不伪造两条作答。
         */
        post: operations["submit_node_self_assessment_api_knowledge__kp_id__self_assessment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Materials */
        get: operations["list_materials_api_materials_get"];
        put?: never;
        /**
         * Upload Material
         * @description 上传一份资料并立即入队处理。
         */
        post: operations["upload_material_api_materials_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/materials/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search Materials
         * @description 调试用混合检索：与后续问答用的是同一条检索链路。
         */
        post: operations["search_materials_api_materials_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/materials/{material_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Material */
        get: operations["get_material_api_materials__material_id__get"];
        put?: never;
        post?: never;
        /** Delete Material */
        delete: operations["delete_material_api_materials__material_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/materials/{material_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Material Content
         * @description 读取已入库的规范化正文；文件路径与原始二进制不对外暴露。
         */
        get: operations["get_material_content_api_materials__material_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/materials/{material_id}/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Material Chunks
         * @description 块预览：用来核对「这份资料实际被切成了什么」。
         */
        get: operations["list_material_chunks_api_materials__material_id__chunks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/materials/{material_id}/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reindex Material */
        post: operations["reindex_material_api_materials__material_id__reindex_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/materials/{material_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Material */
        post: operations["retry_material_api_materials__material_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppendQuestionsRequest */
        AppendQuestionsRequest: {
            /** Question Ids */
            question_ids: string[];
        };
        /** AskRequest */
        AskRequest: {
            /** Question */
            question: string;
        };
        /** AssessmentResponse */
        AssessmentResponse: {
            /**
             * Practice Item Id
             * Format: uuid
             */
            practice_item_id: string;
            /**
             * Kp Id
             * Format: uuid
             */
            kp_id: string;
            /** State */
            state: string;
            /** Reason Code */
            reason_code: string;
            /** Effective Confirmation Count */
            effective_confirmation_count: number;
            /** Manual Credit Count */
            manual_credit_count: number;
            /** Next Review At */
            next_review_at?: string | null;
        };
        /** Body_upload_material_api_materials_post */
        Body_upload_material_api_materials_post: {
            /** File */
            file: string;
        };
        /**
         * ChunkPreviewView
         * @description 块预览：用于「资料到底被切成了什么」的自查。
         */
        ChunkPreviewView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Ordinal */
            ordinal: number;
            /** Heading Path */
            heading_path: string[];
            /** Char Count */
            char_count: number;
            /** Preview */
            preview: string;
            /** Kp Hint Code */
            kp_hint_code?: string | null;
        };
        /** CreateSessionRequest */
        CreateSessionRequest: {
            /**
             * Title
             * @default 新对话
             */
            title: string;
            /**
             * Mode
             * @default builtin
             * @enum {string}
             */
            mode: "builtin" | "user";
        };
        /** FollowupCandidatesRequest */
        FollowupCandidatesRequest: {
            /** Message Id */
            message_id?: string | null;
        };
        /**
         * GapItemView
         * @description 一条毕业条件的进度。key 是稳定机器码，页面按它决定展示方式。
         */
        GapItemView: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Current */
            current: number;
            /** Required */
            required: number;
            /** Satisfied */
            satisfied: boolean;
        };
        /** GeneratePlanRequest */
        GeneratePlanRequest: {
            /** Selected Kp Ids */
            selected_kp_ids: string[];
            /**
             * Budget
             * @default standard
             */
            budget: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Database */
            database: string;
            /**
             * Environment
             * @enum {string}
             */
            environment: "dev" | "test" | "prod";
            /**
             * Retrieval
             * @default unknown
             */
            retrieval: string;
            /** Retrieval Reason */
            retrieval_reason?: string | null;
            /**
             * Worker
             * @default unknown
             */
            worker: string;
            /**
             * Llm Configured
             * @default false
             */
            llm_configured: boolean;
            /** Llm Model */
            llm_model?: string | null;
        };
        /** KnowledgeNodeDetail */
        KnowledgeNodeDetail: {
            node: components["schemas"]["KnowledgeNodeView"];
            /** Questions */
            questions: components["schemas"]["NodeQuestionView"][];
            /** Attempts */
            attempts: components["schemas"]["NodeAttemptView"][];
            /**
             * Materials Ready
             * @default false
             */
            materials_ready: boolean;
        };
        /**
         * KnowledgeNodeView
         * @description 知识树节点；父节点 state 必须为 None，由页面汇总 children。
         */
        KnowledgeNodeView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Subject */
            subject: string;
            /** Ordinal */
            ordinal: number;
            /** Is Assessable */
            is_assessable: boolean;
            /** Summary */
            summary?: string | null;
            /** Learning Goal */
            learning_goal?: string | null;
            /** State */
            state?: string | null;
            /** Next Review At */
            next_review_at?: string | null;
            /** Mastered At */
            mastered_at?: string | null;
            /** Node Self Grade */
            node_self_grade?: string | null;
            /**
             * Manual Credit Count
             * @default 0
             */
            manual_credit_count: number;
            /**
             * Effective Confirmation Count
             * @default 0
             */
            effective_confirmation_count: number;
            /**
             * Has Real Variant
             * @default false
             */
            has_real_variant: boolean;
            /** First Confirmed On */
            first_confirmed_on?: string | null;
            /** Last Confirmed On */
            last_confirmed_on?: string | null;
            /** Day Span */
            day_span?: number | null;
            /**
             * Gap Items
             * @default []
             */
            gap_items: components["schemas"]["GapItemView"][];
            /** Next Step */
            next_step?: string | null;
            /**
             * Required Question Types
             * @default {}
             */
            required_question_types: {
                [key: string]: number;
            };
            /**
             * Excluded Question Types
             * @default []
             */
            excluded_question_types: string[];
            /**
             * Required Skill Tags
             * @default []
             */
            required_skill_tags: string[];
            /**
             * Children
             * @default []
             */
            children: components["schemas"]["KnowledgeNodeView"][];
        };
        /** KnowledgeTreeResponse */
        KnowledgeTreeResponse: {
            /** Nodes */
            nodes: components["schemas"]["KnowledgeNodeView"][];
        };
        /** MaterialChunkListResponse */
        MaterialChunkListResponse: {
            /** Items */
            items: components["schemas"]["ChunkPreviewView"][];
            /** Total */
            total: number;
        };
        /**
         * MaterialContentResponse
         * @description 资料的规范化全文，仅用于阅读；不暴露磁盘路径。
         */
        MaterialContentResponse: {
            /** Title */
            title: string;
            /** Text */
            text?: string | null;
        };
        /**
         * MaterialDetail
         * @description 资料详情：额外带上块数与最近任务。
         */
        MaterialDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Source Type */
            source_type: string;
            /** Original Filename */
            original_filename?: string | null;
            /** Status */
            status: string;
            /** File Size */
            file_size?: number | null;
            /** Active Index Version */
            active_index_version?: string | null;
            /** Last Error Code */
            last_error_code?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Chunk Count
             * @default 0
             */
            chunk_count: number;
            latest_job?: components["schemas"]["MaterialJobView"] | null;
        };
        /**
         * MaterialJobView
         * @description 最近一次处理任务的状态。
         */
        MaterialJobView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Job Type */
            job_type: string;
            /** Status */
            status: string;
            /** Attempts */
            attempts: number;
            /** Max Attempts */
            max_attempts: number;
            /** Error Code */
            error_code?: string | null;
            /** Result Index Version */
            result_index_version?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** MaterialListResponse */
        MaterialListResponse: {
            /** Items */
            items: components["schemas"]["MaterialView"][];
            /** Total */
            total: number;
            /** Stats */
            stats: {
                [key: string]: number;
            };
        };
        /**
         * MaterialUploadResponse
         * @description 上传成功后的即时响应：任务在后台执行，前端轮询详情即可。
         */
        MaterialUploadResponse: {
            material: components["schemas"]["MaterialView"];
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Message */
            message: string;
        };
        /**
         * MaterialView
         * @description 资料列表项。
         */
        MaterialView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Source Type */
            source_type: string;
            /** Original Filename */
            original_filename?: string | null;
            /** Status */
            status: string;
            /** File Size */
            file_size?: number | null;
            /** Active Index Version */
            active_index_version?: string | null;
            /** Last Error Code */
            last_error_code?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * NodeAttemptView
         * @description 练习记录：永久保存的作答历史。
         */
        NodeAttemptView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Question Id
             * Format: uuid
             */
            question_id: string;
            /** Question Stem */
            question_stem: string;
            /** Self Grade */
            self_grade: string;
            /** Objective Result */
            objective_result: string;
            /** Result State */
            result_state: string;
            /** Reason Code */
            reason_code: string;
            /** Submitted At */
            submitted_at: string;
            /** Raw Answer */
            raw_answer?: string | null;
        };
        /**
         * NodeQuestionView
         * @description 知识节点题库里的一道题；这里绝不返回答案与解析。
         */
        NodeQuestionView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Question Type */
            question_type: string;
            /** Difficulty */
            difficulty: string;
            /** Is Variant */
            is_variant: boolean;
            /** Stem */
            stem: string;
            /**
             * Kp Id
             * Format: uuid
             */
            kp_id: string;
        };
        /** NodeSelfAssessmentRequest */
        NodeSelfAssessmentRequest: {
            /** Self Grade */
            self_grade: string;
            /** Idempotency Key */
            idempotency_key: string;
        };
        /** NodeSelfAssessmentResponse */
        NodeSelfAssessmentResponse: {
            /**
             * Kp Id
             * Format: uuid
             */
            kp_id: string;
            /** State */
            state: string;
            /** Reason Code */
            reason_code: string;
            /** Effective Confirmation Count */
            effective_confirmation_count: number;
            /** Manual Credit Count */
            manual_credit_count: number;
            /** Next Review At */
            next_review_at?: string | null;
        };
        /**
         * PlanItemView
         * @description 今日练习卷里的一道题。
         *
         *     这里**绝不返回 correct_answer / explanation**：答案必须通过专门的
         *     GET /api/practice-items/{item_id}/answer 拉取，且该接口是纯读取。
         */
        PlanItemView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Ordinal */
            ordinal: number;
            /**
             * Kp Id
             * Format: uuid
             */
            kp_id: string;
            /** Kp Name */
            kp_name: string;
            /**
             * Question Id
             * Format: uuid
             */
            question_id: string;
            /** Question Type */
            question_type: string;
            /**
             * Question Role
             * @default basic
             */
            question_role: string;
            /** Difficulty */
            difficulty: string;
            /** Stem */
            stem: string;
            /** Options */
            options?: {
                [key: string]: string;
            } | null;
            /**
             * Skill Tags
             * @default []
             */
            skill_tags: string[];
            /** Is Variant */
            is_variant: boolean;
            /**
             * Estimated Minutes
             * @default 5
             */
            estimated_minutes: number;
            /** Completed */
            completed: boolean;
            /** Completed At */
            completed_at?: string | null;
            /** Latest Self Grade */
            latest_self_grade?: string | null;
            /**
             * Is Review
             * @default false
             */
            is_review: boolean;
        };
        /**
         * PracticeItemAnswer
         * @description 答案与解析；纯读取，不写 revealed_at，不影响掌握度与毕业。
         */
        PracticeItemAnswer: {
            /**
             * Practice Item Id
             * Format: uuid
             */
            practice_item_id: string;
            /**
             * Question Id
             * Format: uuid
             */
            question_id: string;
            /** Stem */
            stem: string;
            /** Options */
            options?: {
                [key: string]: string;
            } | null;
            /** Correct Answer */
            correct_answer?: string | null;
            /** Explanation */
            explanation: string;
            /** Question Type */
            question_type: string;
            /** Grading Mode */
            grading_mode: string;
        };
        /**
         * RecommendationItem
         * @description 准备页的一条推荐；reason 是稳定层级码，页面负责映射成中文。
         */
        RecommendationItem: {
            /**
             * Kp Id
             * Format: uuid
             */
            kp_id: string;
            /** Name */
            name: string;
            /** State */
            state: string;
            /** Reason */
            reason: string;
            /**
             * Next Step
             * @default
             */
            next_step: string;
            /**
             * Missing Types
             * @default []
             */
            missing_types: string[];
        };
        /** RenameSessionRequest */
        RenameSessionRequest: {
            /** Title */
            title: string;
        };
        /**
         * SearchHitView
         * @description 一条检索结果：正文 + 出处，供前端做引用卡片与回跳。
         */
        SearchHitView: {
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /**
             * Material Id
             * Format: uuid
             */
            material_id: string;
            /** Material Title */
            material_title: string;
            /** Source Type */
            source_type: string;
            /** Index Version */
            index_version: string;
            /** Ordinal */
            ordinal: number;
            /** Content */
            content: string;
            /** Heading Path */
            heading_path: string[];
            /** Kp Ids */
            kp_ids: string[];
            /** Score */
            score: number;
            /** Vector Rank */
            vector_rank?: number | null;
            /** Keyword Rank */
            keyword_rank?: number | null;
            /** Rerank Score */
            rerank_score?: number | null;
        };
        /**
         * SearchRequest
         * @description 检索请求。
         */
        SearchRequest: {
            /** Query */
            query: string;
            /**
             * Top K
             * @default 6
             */
            top_k: number;
            /**
             * Candidate K
             * @default 20
             */
            candidate_k: number;
            /** Material Ids */
            material_ids?: string[] | null;
            /** Source Types */
            source_types?: string[] | null;
            /** Kp Ids */
            kp_ids?: string[] | null;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            /** Hits */
            hits: components["schemas"]["SearchHitView"][];
            /**
             * Degraded
             * @default false
             */
            degraded: boolean;
            /** Degraded Reasons */
            degraded_reasons?: string[];
            /**
             * Vector Candidates
             * @default 0
             */
            vector_candidates: number;
            /**
             * Keyword Candidates
             * @default 0
             */
            keyword_candidates: number;
            /**
             * Reranked
             * @default false
             */
            reranked: boolean;
        };
        /** SubmitSelfAssessmentRequest */
        SubmitSelfAssessmentRequest: {
            /** Self Grade */
            self_grade: string;
            /** Idempotency Key */
            idempotency_key: string;
            /** Raw Answer */
            raw_answer?: string | null;
            /** Selected Option */
            selected_option?: string | null;
        };
        /**
         * TodayActive
         * @description 已有活动练习卷（或已完成）。
         */
        TodayActive: {
            /** Status */
            status: string;
            /**
             * Plan Id
             * Format: uuid
             */
            plan_id: string;
            /** Study Date */
            study_date: string;
            /** Completed Count */
            completed_count: number;
            /** Total Count */
            total_count: number;
            /** Items */
            items: components["schemas"]["PlanItemView"][];
            /** Focus Item Id */
            focus_item_id?: string | null;
            /** Summary Kps */
            summary_kps: components["schemas"]["TodaySummaryKp"][];
            /**
             * Type Summary
             * @default {}
             */
            type_summary: {
                [key: string]: number;
            };
            /**
             * Estimated Minutes
             * @default 0
             */
            estimated_minutes: number;
            /**
             * Remaining Minutes
             * @default 0
             */
            remaining_minutes: number;
        };
        /**
         * TodaySetup
         * @description 当天还没有活动练习卷：展示准备页，等用户确认后才生成。
         */
        TodaySetup: {
            /**
             * Status
             * @default setup
             */
            status: string;
            /** Study Date */
            study_date: string;
            /** Recommendations */
            recommendations: components["schemas"]["RecommendationItem"][];
        };
        /** TodaySummaryKp */
        TodaySummaryKp: {
            /**
             * Kp Id
             * Format: uuid
             */
            kp_id: string;
            /** Name */
            name: string;
            /** Completed Count */
            completed_count: number;
            /** Total Count */
            total_count: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_sessions_api_chat_sessions_get: {
        parameters: {
            query?: {
                mode?: ("builtin" | "user") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_api_chat_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_api_chat_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_session_api_chat_sessions__session_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_messages_api_chat_sessions__session_id__messages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_api_chat_sessions__session_id__answers_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_stream_api_chat_sessions__session_id__answers_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    followup_candidates_api_chat_sessions__session_id__followup_candidates_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["FollowupCandidatesRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_confused_api_chat_sessions__session_id__mark_confused_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_today_plan_api_plans_today_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodaySetup"] | components["schemas"]["TodayActive"];
                };
            };
        };
    };
    generate_today_plan_api_plans_today_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeneratePlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodayActive"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_plan_items_api_plans__plan_id__items_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodayActive"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    append_plan_questions_api_plans__plan_id__questions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppendQuestionsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodayActive"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_practice_item_answer_api_practice_items__item_id__answer_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeItemAnswer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_self_assessment_api_practice_items__item_id__self_assessments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitSelfAssessmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_knowledge_tree_api_knowledge_tree_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeTreeResponse"];
                };
            };
        };
    };
    read_knowledge_node_api_knowledge__kp_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kp_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeNodeDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_node_self_assessment_api_knowledge__kp_id__self_assessment_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kp_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NodeSelfAssessmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeSelfAssessmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_materials_api_materials_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                status?: string | null;
                source_type?: string | null;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_material_api_materials_post: {
        parameters: {
            query: {
                title: string;
                source_type?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_material_api_materials_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_materials_api_materials_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_material_api_materials__material_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_material_api_materials__material_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_material_content_api_materials__material_id__content_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialContentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_material_chunks_api_materials__material_id__chunks_get: {
        parameters: {
            query?: {
                limit?: number;
                focus_chunk_id?: string | null;
            };
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialChunkListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reindex_material_api_materials__material_id__reindex_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialJobView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_material_api_materials__material_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialJobView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
