"""add rag core tables and document jobs

Revision ID: 4d3a135231c4
Revises: e265f44be662
Create Date: 2026-09-18 20:02:41.658186

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4d3a135231c4'
down_revision: str | None = 'e265f44be662'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_hash', sa.String(length=64), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('active_index_version', sa.String(length=64), nullable=True),
    sa.Column('last_error_code', sa.String(length=80), nullable=True),
    sa.Column('last_error_message', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_materials'))
    )
    op.create_index(op.f('ix_materials_status'), 'materials', ['status'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('material_id', sa.Uuid(), nullable=False),
    sa.Column('index_version', sa.String(length=64), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.Column('heading_path', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('kp_hint_code', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_document_chunks_material_id_materials'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunks')),
    sa.UniqueConstraint('material_id', 'index_version', 'ordinal', name='chunk_material_version_ordinal')
    )
    op.create_index(op.f('ix_document_chunks_index_version'), 'document_chunks', ['index_version'], unique=False)
    op.create_index(op.f('ix_document_chunks_material_id'), 'document_chunks', ['material_id'], unique=False)
    op.create_table('document_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('material_id', sa.Uuid(), nullable=False),
    sa.Column('job_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('result_index_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("job_type IN ('ingest','reindex','delete')", name=op.f('ck_document_jobs_job_type_valid')),
    sa.CheckConstraint("status IN ('pending','running','retry','succeeded','failed')", name=op.f('ck_document_jobs_job_status_valid')),
    sa.CheckConstraint('attempts >= 0 AND max_attempts >= 1', name=op.f('ck_document_jobs_job_attempt_range')),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_document_jobs_material_id_materials'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_jobs'))
    )
    op.create_index(op.f('ix_document_jobs_lease_until'), 'document_jobs', ['lease_until'], unique=False)
    op.create_index(op.f('ix_document_jobs_material_id'), 'document_jobs', ['material_id'], unique=False)
    op.create_index(op.f('ix_document_jobs_next_run_at'), 'document_jobs', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_document_jobs_status'), 'document_jobs', ['status'], unique=False)
    op.create_table('chunk_knowledge_points',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('kp_id', sa.Uuid(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], name=op.f('fk_chunk_knowledge_points_chunk_id_document_chunks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kp_id'], ['knowledge_points.id'], name=op.f('fk_chunk_knowledge_points_kp_id_knowledge_points'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunk_knowledge_points')),
    sa.UniqueConstraint('chunk_id', 'kp_id', name='chunk_kp_unique')
    )
    op.create_index(op.f('ix_chunk_knowledge_points_chunk_id'), 'chunk_knowledge_points', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_chunk_knowledge_points_kp_id'), 'chunk_knowledge_points', ['kp_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunk_knowledge_points_kp_id'), table_name='chunk_knowledge_points')
    op.drop_index(op.f('ix_chunk_knowledge_points_chunk_id'), table_name='chunk_knowledge_points')
    op.drop_table('chunk_knowledge_points')
    op.drop_index(op.f('ix_document_jobs_status'), table_name='document_jobs')
    op.drop_index(op.f('ix_document_jobs_next_run_at'), table_name='document_jobs')
    op.drop_index(op.f('ix_document_jobs_material_id'), table_name='document_jobs')
    op.drop_index(op.f('ix_document_jobs_lease_until'), table_name='document_jobs')
    op.drop_table('document_jobs')
    op.drop_index(op.f('ix_document_chunks_material_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_index_version'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_materials_status'), table_name='materials')
    op.drop_table('materials')
    # ### end Alembic commands ###