"""add question taxonomy and per-kp mastery policy

Revision ID: 4e69a0e83a3b
Revises: 4d3a135231c4
Create Date: 2026-09-19 11:16:56.633668

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4e69a0e83a3b'
down_revision: str | None = '4d3a135231c4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kp_mastery_policies',
    sa.Column('kp_id', sa.Uuid(), nullable=False),
    sa.Column('min_confirmations', sa.Integer(), nullable=False),
    sa.Column('min_real_questions', sa.Integer(), nullable=False),
    sa.Column('required_question_types', sa.JSON(), nullable=False),
    sa.Column('excluded_question_types', sa.JSON(), nullable=False),
    sa.Column('required_skill_tags', sa.JSON(), nullable=False),
    sa.Column('required_variant_count', sa.Integer(), nullable=False),
    sa.Column('min_day_span', sa.Integer(), nullable=False),
    sa.Column('manual_mastered_credit', sa.Integer(), nullable=False),
    sa.Column('review_intervals_days', sa.JSON(), nullable=False),
    sa.Column('max_evidence_window', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('manual_mastered_credit >= 0', name=op.f('ck_kp_mastery_policies_kp_policy_manual_credit')),
    sa.CheckConstraint('min_confirmations >= 1', name=op.f('ck_kp_mastery_policies_kp_policy_min_confirmations')),
    sa.CheckConstraint('min_day_span >= 0', name=op.f('ck_kp_mastery_policies_kp_policy_day_span')),
    sa.CheckConstraint('min_real_questions >= 1', name=op.f('ck_kp_mastery_policies_kp_policy_min_real_questions')),
    sa.CheckConstraint('required_variant_count >= 0', name=op.f('ck_kp_mastery_policies_kp_policy_variant_count')),
    sa.ForeignKeyConstraint(['kp_id'], ['knowledge_points.id'], name=op.f('fk_kp_mastery_policies_kp_id_knowledge_points'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('kp_id', name=op.f('pk_kp_mastery_policies'))
    )
    op.add_column('questions', sa.Column('question_role', sa.String(length=30), nullable=False, server_default='basic'))
    op.add_column('questions', sa.Column('skill_tags', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('questions', sa.Column('estimated_minutes', sa.Integer(), nullable=False, server_default='5'))
    # 给既有行兜底之后立刻去掉默认值：
    # 默认值只用于“老数据迁移”，之后所有写入都必须由应用显式给值，
    # 否则新插入的题目会在没人察觉的情况下悄悄拿到一个语义不明的默认角色。
    op.alter_column('questions', 'question_role', server_default=None)
    op.alter_column('questions', 'skill_tags', server_default=None)
    op.alter_column('questions', 'estimated_minutes', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'estimated_minutes')
    op.drop_column('questions', 'skill_tags')
    op.drop_column('questions', 'question_role')
    op.drop_table('kp_mastery_policies')
    # ### end Alembic commands ###