"""给 chat_messages 加插入序号 seq，让消息顺序确定且与业务语义一致。

为什么需要它：
user 消息与 assistant 占位是在**同一个事务**里写入的，
`created_at` 的 `server_default=now()` 在事务内取同一个值 —— 两条消息时间完全相同。
而旧排序只有 `created_at`，于是两者的先后成了数据库的偶然结果：
表现为刷新问答页后「回答出现在问题前面」，并且时有时无（随机复现）。

用 `id`（随机 UUID）当兜底键只能保证「稳定」，不能保证「正确」——
它可能稳定地把 assistant 排在 user 前面。

因此加一列 `seq`（bigserial）：它是插入顺序的单调序号，
排序变为 `ORDER BY seq`，既确定又符合「先问后答」的业务语义。

Revision ID: 7d2e5a9c4b31
Revises: 4c8a2f1b7d95
"""

from alembic import op

revision = "7d2e5a9c4b31"
down_revision = "4c8a2f1b7d95"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # 用 identity 列（PostgreSQL 10+ 的标准写法）自动递增。
    # 存量行按 created_at + ctid 的顺序补号，尽量贴近原本的插入顺序。
    op.execute("ALTER TABLE chat_messages ADD COLUMN seq bigint GENERATED BY DEFAULT AS IDENTITY")
    op.execute(
        """
        WITH ordered AS (
            SELECT id, row_number() OVER (ORDER BY created_at, ctid) AS rn
            FROM chat_messages
        )
        UPDATE chat_messages m
        SET seq = ordered.rn
        FROM ordered
        WHERE m.id = ordered.id
        """
    )
    # 补号后把 identity 起点推到当前最大值之后，避免新插入的行撞号。
    op.execute(
        """
        SELECT setval(
            pg_get_serial_sequence('chat_messages', 'seq'),
            COALESCE((SELECT max(seq) FROM chat_messages), 0) + 1,
            false
        )
        """
    )
    op.execute("ALTER TABLE chat_messages ALTER COLUMN seq SET NOT NULL")
    op.create_index("ix_chat_messages_seq", "chat_messages", ["seq"])


def downgrade() -> None:
    op.drop_index("ix_chat_messages_seq", table_name="chat_messages")
    op.drop_column("chat_messages", "seq")
