"""create learning core tables

Revision ID: e265f44be662
Revises: 
Create Date: 2026-09-18 18:55:05.234110

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e265f44be662'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('study_date', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_plans')),
    sa.UniqueConstraint('study_date', name='daily_plan_date')
    )
    op.create_table('knowledge_points',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=80), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('is_assessable', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('learning_goal', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['knowledge_points.id'], name=op.f('fk_knowledge_points_parent_id_knowledge_points')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_points')),
    sa.UniqueConstraint('code', name=op.f('uq_knowledge_points_code'))
    )
    op.create_table('kp_states',
    sa.Column('kp_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('evidence_window', sa.JSON(), nullable=False),
    sa.Column('review_stage', sa.Integer(), nullable=False),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mastered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('node_self_grade', sa.String(length=30), nullable=True),
    sa.Column('manual_credit_count', sa.Integer(), nullable=False),
    sa.Column('manual_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kp_id'], ['knowledge_points.id'], name=op.f('fk_kp_states_kp_id_knowledge_points'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('kp_id', name=op.f('pk_kp_states'))
    )
    op.create_table('learning_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kp_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('evidence_level', sa.String(length=30), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['kp_id'], ['knowledge_points.id'], name=op.f('fk_learning_events_kp_id_knowledge_points'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_events')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_learning_events_idempotency_key'))
    )
    op.create_index(op.f('ix_learning_events_kp_id'), 'learning_events', ['kp_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kp_id', sa.Uuid(), nullable=False),
    sa.Column('question_type', sa.String(length=30), nullable=False),
    sa.Column('grading_mode', sa.String(length=30), nullable=False),
    sa.Column('stem', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('is_variant', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('variant_group', sa.String(length=120), nullable=True),
    sa.Column('difficulty', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kp_id'], ['knowledge_points.id'], name=op.f('fk_questions_kp_id_knowledge_points'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions'))
    )
    op.create_index(op.f('ix_questions_kp_id'), 'questions', ['kp_id'], unique=False)
    op.create_table('practice_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('kp_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_self_grade', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kp_id'], ['knowledge_points.id'], name=op.f('fk_practice_items_kp_id_knowledge_points')),
    sa.ForeignKeyConstraint(['plan_id'], ['daily_plans.id'], name=op.f('fk_practice_items_plan_id_daily_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_practice_items_question_id_questions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practice_items')),
    sa.UniqueConstraint('plan_id', 'ordinal', name='practice_item_plan_ordinal'),
    sa.UniqueConstraint('plan_id', 'question_id', name='practice_item_plan_question')
    )
    op.create_index(op.f('ix_practice_items_kp_id'), 'practice_items', ['kp_id'], unique=False)
    op.create_index(op.f('ix_practice_items_plan_id'), 'practice_items', ['plan_id'], unique=False)
    op.create_table('question_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('practice_item_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('kp_id', sa.Uuid(), nullable=False),
    sa.Column('raw_answer', sa.Text(), nullable=True),
    sa.Column('objective_result', sa.String(length=20), nullable=False),
    sa.Column('self_grade', sa.String(length=30), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('result_state', sa.String(length=30), nullable=False),
    sa.Column('reason_code', sa.String(length=80), nullable=False),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['kp_id'], ['knowledge_points.id'], name=op.f('fk_question_attempts_kp_id_knowledge_points')),
    sa.ForeignKeyConstraint(['practice_item_id'], ['practice_items.id'], name=op.f('fk_question_attempts_practice_item_id_practice_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_question_attempts_question_id_questions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_attempts')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_question_attempts_idempotency_key'))
    )
    op.create_index(op.f('ix_question_attempts_kp_id'), 'question_attempts', ['kp_id'], unique=False)
    op.create_index(op.f('ix_question_attempts_practice_item_id'), 'question_attempts', ['practice_item_id'], unique=False)
    op.create_index(op.f('ix_question_attempts_question_id'), 'question_attempts', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_attempts_question_id'), table_name='question_attempts')
    op.drop_index(op.f('ix_question_attempts_practice_item_id'), table_name='question_attempts')
    op.drop_index(op.f('ix_question_attempts_kp_id'), table_name='question_attempts')
    op.drop_table('question_attempts')
    op.drop_index(op.f('ix_practice_items_plan_id'), table_name='practice_items')
    op.drop_index(op.f('ix_practice_items_kp_id'), table_name='practice_items')
    op.drop_table('practice_items')
    op.drop_index(op.f('ix_questions_kp_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_learning_events_kp_id'), table_name='learning_events')
    op.drop_table('learning_events')
    op.drop_table('kp_states')
    op.drop_table('knowledge_points')
    op.drop_table('daily_plans')
    # ### end Alembic commands ###